In [19]:
import numpy as np

# our second column data is grossly mis-scaled! What do we do?
X_train = np.array([[ 1., -100000.,  2.], [ 2.,  0.,  0.], [ 0.,  100000., -1.]])

X_train

array([[ 1.e+00, -1.e+05,  2.e+00],
       [ 2.e+00,  0.e+00,  0.e+00],
       [ 0.e+00,  1.e+05, -1.e+00]])

In [20]:
# We NORMALIZE each column to fit in the same "ballpark" without modifying each column's distribution

(X_train[:,0]-X_train[:,0].mean())/X_train[:,0].std()
(X_train[:,1]-X_train[:,1].mean())/X_train[:,1].std()
(X_train[:,2]-X_train[:,2].mean())/X_train[:,2].std()

array([ 1.33630621, -0.26726124, -1.06904497])

In [16]:
(X_train-X_train.mean(axis=0))/X_train.std(axis=0)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [21]:
(X_train-X_train.mean(axis=0))/X_train.std(axis=0)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])